backend:
  name: git-gateway
  branch: master

# Queue updates for manual review before publishing
publish_mode: editorial_workflow

# Uploaded pictures go here
media_folder: "assets/images"

# Disable new builds for every requested change
show_preview_links: false

# Allow for local development when running the proxy
local_backend: true

# CMS configurations
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "/pages/index.html"
        fields:
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
          - {label: Button Text, name: buttonText, widget: string}
          - {label: Button Link, name: buttonLink, widget: string}
          - {label: Background Position X, name: backgroundPositionX, widget: string}
          - {label: Background Position Y, name: backgroundPositionY, widget: string}
          - {label: Desktop Image, name: desktopImage, widget: image}
          - {label: Mobile Image, name: mobileImage, widget: image}
      - label: "Launches"
        name: "launches"
        file: "/pages/launches/index.html"
        fields:
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
          - {label: Button Text, name: buttonText, widget: string}
          - {label: Background Position X, name: backgroundPositionX, widget: string}
          - {label: Background Position Y, name: backgroundPositionY, widget: string}
          - {label: Desktop Image, name: desktopImage, widget: image}
          - {label: Mobile Image, name: mobileImage, widget: image}
          - {label: Youtube Link, name: youtubeLink, widget: string}
          - {label: Youtube ID, name: youtubeId, widget: string}
          - {label: Copy Left, name: copyLeft, widget: markdown}
          - {label: Copy Right, name: copyRight, widget: markdown}
