backend:
  name: git-gateway
  branch: master

# Queue updates for manual review before publishing
publish_mode: editorial_workflow

# Uploaded pictures go here
media_folder: "assets/images"

# Disable new builds for every requested change
show_preview_links: false

# Allow for local development when running the proxy
local_backend: true

# CMS configurations
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "/pages/index.html"
        fields:
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
